### ISSUE TITLE
研究平台推荐

### ISSUE THREAD

**Issue by izhouping** [izhouping/KPA#1]
## 推荐格式
【推荐对象1】
【推荐理由】

【推荐对象2】
【推荐理由】

【推荐对象3】
【推荐理由】

## 截止时间
- 20190109  24:00

**Comment by zhangllu** [comment]
### 【推荐对象1】
###    [奴隶社会](https://chuansongme.com/account/nulishehui/recent)
### 【推荐理由】
#### 1.公众号简介：
###### 奴隶社会就是两个人，基于自觉自愿的原则，用绳命玩的一场 Cosplay 的游戏。 华奴在挨踢界混迹多年，身经百战，伤痕累累； 诺主为某高大上咨询公司合伙人。俩人有仨娃， 内心皆文青屌丝，执迷于做点儿自己喜欢的事儿，不枉此生。
#### 2.公众号创始人-李一诺简介：
###### 百度百科：诺主即李一诺，[清华大学](https://baike.baidu.com/item/%E6%B8%85%E5%8D%8E%E5%A4%A7%E5%AD%A6)生物系本科，[加州大学洛杉矶分校](https://baike.baidu.com/item/%E5%8A%A0%E5%B7%9E%E5%A4%A7%E5%AD%A6%E6%B4%9B%E6%9D%89%E7%9F%B6%E5%88%86%E6%A0%A1/4014219)分子生物学博士，2005年开始进入[麦肯锡](https://baike.baidu.com/item/%E9%BA%A6%E8%82%AF%E9%94%A1)公司<sup> [1]</sup>  ，2015年6月李一诺开始担任[比尔和梅琳达·盖茨基金会](https://baike.baidu.com/item/%E6%AF%94%E5%B0%94%E5%92%8C%E6%A2%85%E7%90%B3%E8%BE%BE%C2%B7%E7%9B%96%E8%8C%A8%E5%9F%BA%E9%87%91%E4%BC%9A/3836213)北京代表处首席代表<sup> [2]</sup>  。2016年3月16日，李一诺当选2016年“[全球青年领袖](https://baike.baidu.com/item/%E5%85%A8%E7%90%83%E9%9D%92%E5%B9%B4%E9%A2%86%E8%A2%96/2079007)”。
###### 知乎李一诺个人主页简介：一土学校创始人，前麦肯锡全球合伙人， 内心文青屌丝；归国女博士，有马甲线的仨娃妈。希望永远25岁 － 除了为臭美，希望永远保持年轻简单的内心和求知欲，把纷繁复杂的问题简单化， 和所遇到的人做真朋友， 和娃做真朋友，和老公永远谈恋爱。和老公YY了个微信公众号， 请搜索”奴隶社会“或 “nulishehui" 关注，不端不装有趣有梦，听现实的理想主义者讲述自己的故事。

#### 3.我了解到公众号【奴隶社会】的渊源
###### 由心理学博士李松蔚的一篇文章了解到[一土教育](https://www.etuschool.org/about-us-zh),然后了解到创始人李一诺。

#### 4.李一诺老公简介
###### 申华章，中国科学技术大学本科，加州理工大学生物学硕士；微信公众号“奴隶社会”发起人运营人，社群 App 磁场共同创始人，依托 IT 技术的个性化教育项目一土学校共同创始人。前汽车O2O“卡拉丁”合伙人；“活在未来”的深度思考者。
###### 自述：创业很多年，从互联网电商、社区、游戏，到移动互联网App，到O2O，再回到我的真爱——社交，教育。一路上踩了很多坑，也收获了很多。 2014年创立自媒体“奴隶社会”，第一的现实的理想主义者社区，不花一分钱推广费用，没有一个全职员工，聚集来自咨询，投行，VC，创业者，大公司，高校等超过40万读者，出了四本书，全球举办十几场线下活动。在这个过程中积累了真实的自媒体运营经验。

#### 5.相关知识付费产品
###### 【诺言】社区，人生故事与职场干货的集散地，不端不装、有趣有梦的朋友圈。这里有大咖，有行动，视野在全球，交往就在家门口。
###### 课程覆盖系统思维，时间管理，情绪管理以及人生选择等内容，定期举办的直播互动和线下聚会均可与各界大咖直接交流。
###### 往期嘉宾包括「经济学人」中国区总裁刘倩，「麦肯锡」全球董事合伙人彭壮壮等。诺友在社区内还可以通过发布动态、群组、文章、活动等功能相互交流，共同学习成长。
###### 加入社区费用：1年会员999元，2年会员1998元。

###### 知识付费课程介绍-[诺言](https://hybrid.cichang.net/courses/595630474dd6a31f725240a8?)

### 【推荐对象2】
### [远读重洋](https://web.okjike.com/topic/59a76f8404a05a0011f7c722/official)
### 【推荐理由】
#### 1.公众号简介
###### 全球新知第一站。
###### 涉及商业、个人成长、心理、科技等内容。

#### 2.创始人简介
###### 孙思远。远读重洋创始人，真格基金媒体顾问。曾担任新浪网科技/财经事业部美东地区主管、纽约站首席记者，曾专访巴菲特、格林斯潘、马云等政商领袖。曾任互联网金融千人会（IFC1000）华尔街分会执行秘书长。毕业于美国南加州大学（USC），经济学硕士。LinkedIn专栏作家、新浪财经专栏作家。
#### 3.公司简介
###### [北京远读重洋信息科技有限公司](https://www.qichacha.com/firm_28add434360b56ecf9829429e5005955.html)

###### 远读重洋是一家由知名媒体人、金牌编辑、名校毕业生组成的知识服务公司，由真格基金徐小平老师投资，聚焦于尚未引进的海外前沿内容，旨在打破知识的国界。原创文章、音频节目，被推荐发布至「罗辑思维•得到」「喜马拉雅」「分答」「36氪」「亚马逊中国」「领英专栏」等各大平台。
#### 4.知识付费产品

###### [远读专栏](https://appfo0glisv2026.h5.xiaoeknow.com/content_page/eyJ0eXBlIjozLCJhcHBfaWQiOiJhcHBGTzBnTGlTdjIwMjYiLCJyZXNvdXJjZV90eXBlIjoiIiwicHJvZHVjdF9pZCI6InBfNWMyMzdiMDUzMGMwYl9VWVlNNElsTSIsImNoYW5uZWxfaWQiOiIiLCJyZXNvdXJjZV9pZCI6IiIsInNoYXJlX3VzZXJfaWQiOiJ1XzVjMzU2YWM2Y2M1ODdfeWluZ3RrMmdoWCIsInNoYXJlX3R5cGUiOjJ9?entry=2&entry_type=2001)
###### [远读听书馆](https://appfo0glisv2026.h5.xiaoeknow.com/mp_more/eyJpZCI6IjExNzIzNSIsImNoYW5uZWxfaWQiOiIiLCJjb21wb25lbnRfaWQiOjIzOTY5Njh9)


### 【推荐对象3】
### [认真想](https://chuansongme.com/account/Reason-Edu/recent)
### 【推荐理由】
#### 1.简介
###### [致力于普及批判性思维与通识教育](https://zhuanlan.zhihu.com/p/25376735)

#### 2.公司简介
###### [北京认真想教育科技有限公司](https://www.qichacha.com/cbase_463e55313dc6094779f902d703d311d6)

#### 3.创始人简介
###### 李万中，网名Andy Lee。北京认真想教育科技有限公司创始人，擅长批判性思维与通识教育课程的研发与讲授。与知乎合作出版的电子书《拔起逻辑之剑》曾长期处于亚马逊逻辑学类书籍销售榜第一名。也是教育无边界字幕组的优秀翻译。17年出版了书籍[《思维的利剑》](https://book.douban.com/subject/27030818/)

#### 4.认真想课程介绍
###### [初级课程](https://zhuanlan.zhihu.com/p/25860227)

**Comment by izhouping** [comment]
【推荐对象1】得到/罗辑思维
【推荐理由】知识付费领域的头部平台。2017年11月8日，罗辑思维入选时代影响力·中国商业案例TOP30。队员康峰同学，也在作业中对它进行过研究 [【罗辑思维】](https://m.openmindclub.com/stu/IA003/work/75a0a047-bed1-40cc-9830-46c7e89937b0/answer/3971c7a6-081e-487f-8fd1-fc1d750255f2) ，可以为团队节省大量时间。冁然同学研读过得到品控手册。这些都是宝贵的经验。

【推荐对象2】喜马拉雅
【推荐理由】同样入选时代影响力·中国商业案例TOP30。在APP STORE的图书类别里，长期排名第一。深耕音频领域，拥有海量用户。

【推荐对象3】知识星球
【推荐理由】和之前的平台相比，略有不同。深度连接铁杆粉丝,运营高品质社群。前段时间刚加入阳老师的安人书院，很好奇它的玩法是什么。虽不是头部企业，但好在形式特殊。

**Comment by louwuxia** [comment]
因自身没有公众号和大牛的粉丝流量，所以需要把课程放在高流量平台，我比较推荐热门的APP，已经形成一定规模，有流量型学习平台；
【推荐对象1】得到
【推荐理由】参考APP Store中排行榜中得到APP，搜索“学习”，推荐人气APP排名在第一个；查询百度以及问身边朋友推荐比较多；
【推荐对象2】混沌大学
【推荐对象2】知识星球

| 平台       | 平台介绍                                                     | 成立时间 | 课程类型                                                 | 平台讲师   | 平台注册量 | 总结                           |
| ---------- | ------------------------------------------------------------ | -------- | -------------------------------------------------------- | ---------- | ---------- | ------------------------------ |
| 得到       | 罗辑思维专注于移动互联网知识付费业务，通过旗下“罗辑思维微信公众号”以及“得到APP”两大核心产品触达用户，为用户在时间碎片化背景下提供单位时间价值最大化的跨界、终身学习解决方案，隶属于北京思维造物信息科技有限公司。 | 2014-6   | 能力学院、商学院、科学学院、视野学院、社科学院、人文学院 | 多维度     |            | 推荐                           |
| 馒头商学院 | 馒头商学院是一家互联网行业在线教育平台，专注于帮助企业实现互联网转型，为用户提供由互联网公司的产品、运营、营销资深大咖教授的在线课程，并在线上开展公开课直播分享从业经验、案例，通过线上微课和线下相结合的方式实现社群学习。 | 2014-5   | 新媒体、营销、运营、产品、市场、写作                     | 企业管理者 |            | 主打增长类，课程较少； |
| 混沌大学   | 混沌大学是一家互联网行业课程教育机构，包括产品学院、创业学院、商学院、创新学院四个学院，通过顶级教授、商业领袖、世界名师、投资人、产品经理等组成的优秀导师团，为学员提供优质的创新课程，并将颠覆、创新理论运用到企业实践。 | 2015-5   | 产品学院、创业学院、商学院、创新学院                     | 企业家     |            | 推荐                           |
| 知识星球   | 知识星球是一个内容创作付费社区，以分组朋友圈的形式进行知识分享，为用户提供实现知识变现工具，内容创作者可以建立圈子，连接铁杆粉丝，运营高品质社群，致力于让团队、社群可以安全地分享文件和信息。 | 2014-6   | 大牛为主链接粉丝                                         | 知识大牛   |            | 推荐                           |
| 喜马拉雅   | 喜马拉雅FM是一个音频分享平台，也是提供高质量声音发现和分享的音频媒体。平台为用户提供了各类有声小说、财经报道、儿歌笑话的各类内容，并能自动推送用户关注的个人电台的声音更新，以及关注的内容，同时也支持用户上传分享自己或自己喜欢的声音到平台。 | 2012-08  | 个人提升（情商、智慧读书等）                             | 多维度     |            | 专注音频，暂不推荐             |

**Comment by CathrineintheCR** [comment]
## 【推荐对象1】得到
### 【推荐理由】普及度与美誉度都较高
1.  普及度较高: 得到APP在知识付费领域的普及度较高，安卓总下载量:69,556,432。苹果应用图书榜(免费)排名第六名。
2.  口碑较好:业界对对得到的评价较好
3.  套利模式价值:公司发展快
 从2013年的天使轮几百万元，到2015年发布得到APP 1.0版本，仅仅2年的2017已拿到D轮80亿人民币，可见其发展势头及套利模式被行业大佬认可。

## 【推荐对象2】喜马拉雅
### 【推荐理由】流量大
1.  用户量及下载量大:
喜马拉雅APP在安卓总下载量:1,387,687,261。苹果应用榜(免费)第八名，图书榜(免费)第一名。
2.  总体估值较高:
喜马拉雅的2018年估值达到36亿美金。

## 【推荐对象3】混沌大学
### 【推荐理由】
1.  口碑极好
2.  商业模式简单
3.  学员高端，拥有未来无限可套利潜能

### 总结
三家公司都是属于知识付费领域里面的佼佼者，无论是普及度还是口碑都颇为被用户和投资者者认可。事实上，虽然三家都是知识付费领域，但各自的套利模式却大有区别，三家凭借不同的模式却都能获得巨大套利，这背后一定有值得我们研究学习、以及可以归纳的一些底层规律。

**三家模式之我的解析**
- 得到的运营模式，偏强运营，以脱不花为首的企业管理团无论是在官方的品控手册的工作流程制定上，还是在得到直播和例会中，展现出来的都是作为管理者对每款课程的品质提出的极高要求，俨然一副强势管理作风。得到在短时间内获得大量融资，可见其运营及商业模式有值得研究之处。

- 喜马拉雅的运营则更倾向于是一个平台商，虽然喜马拉雅已经购入了多项产品著作权，但相对于他庞大的上架商品来说，比例还是极小的。喜马拉雅无论是对上架节目还是讲师都采取的是“自治”风格。可能多数知名讲师也是看重了这种没有拘束，同时喜马拉雅的流量的确惊人，才与之合作。这种弱运营做大流量的方式也为喜马拉雅带来了巨大的估值，这也值得研究。

- 混沌大学的目的是想打造一个没有门槛的大学，但目前来看还在发展的道路上。但是，不得不承认的是，混沌的口碑极好，且他的学员基本定位在高管、创业者及以上。即便混沌到目前为止在投融资上面都没有太大的动作，估值也不对外宣称，我却认为这里面还蕴藏着巨大套利变现商机或者说潜能还为展现。混沌的学员定位就注定了它可以带来极佳的资源优势，并且混沌的运营模式是走班级运营的强社群模式，非常有利于建立学员之间的情感联系。等过几年，这一波能量积蓄起来之后，超过某个临界点之后，混沌或者以混沌为中心的这一波群体简直可以放量无穷啊。所以也值得现在研究研究。

**Comment by izhouping** [comment]
综合大家的意见，最终选择 **得到** 、 **喜马拉雅** 、 **混沌大学** 作为分析对象。
